name: Compile test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typ_file_name: [sample, sample-en]
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-cjk-extra
      - name: Compile
        run: typst compile ${{ matrix.typ_file_name }}.typ
